import React from "react";
import LegalPage from "./LegalPage";

export function PrivacyPolicy() {
  return (
    <LegalPage title="Privacy Policy" updatedOn="Jan 2026">
      <p>
        This policy explains what data Placemint collects, why we collect it, and how it's used. We keep it short because we collect very little.
      </p>
      <h2>What we collect</h2>
      <ul>
        <li>Account basics: name, email, password hash (bcrypt), profile image if you sign in with Google.</li>
        <li>Profile you enter: college, target role, graduation year.</li>
        <li>Your resume PDF (when uploaded), the extracted text, and the AI's analysis.</li>
        <li>OA attempts, answers, coding submissions, interview transcripts, and generated reports.</li>
        <li>Payment metadata (Razorpay order ids). We never see your card details; Razorpay handles that.</li>
      </ul>
      <h2>What we don't collect</h2>
      <ul>
        <li>No behavioural ad tracking, no third-party pixels.</li>
        <li>No microphone/camera access.</li>
      </ul>
      <h2>How we use it</h2>
      <p>
        Strictly to run the product: tailoring OA questions to your role, generating your resume analysis, grading your interview, showing your dashboard. We do not sell your data.
      </p>
      <h2>Data deletion</h2>
      <p>
        Email <a href="mailto:hello@placemint.app" className="text-pm-primary-dark underline">hello@placemint.app</a> to delete your account. We'll wipe your profile, attempts, and resume text within 7 days.
      </p>
    </LegalPage>
  );
}

export function TermsOfService() {
  return (
    <LegalPage title="Terms of Service" updatedOn="Jan 2026">
      <p>
        By using Placemint you agree to these terms. If you don't, please don't use the service.
      </p>
      <h2>What we provide</h2>
      <p>
        A placement-prep simulator that runs realistic OA and interview flows for 14 Indian tech companies. Questions are generated by AI, so they'll approximate real company patterns but they aren't official company assessments.
      </p>
      <h2>Your account</h2>
      <ul>
        <li>You're responsible for keeping your password safe.</li>
        <li>One account per person. Don't share your login.</li>
        <li>Don't use Placemint to harass others or automate abusive traffic.</li>
      </ul>
      <h2>Content &amp; IP</h2>
      <ul>
        <li>You keep ownership of your resume and answers.</li>
        <li>Placemint owns the platform, generated questions, and AI-produced reports.</li>
        <li>You may screenshot your own results for personal use.</li>
      </ul>
      <h2>Service availability</h2>
      <p>
        We do our best to stay up, but this is a beta. AI providers occasionally rate-limit or fail; Placemint isn't liable for missed placement opportunities or grading edge cases.
      </p>
      <h2>Termination</h2>
      <p>
        We may suspend accounts that violate these terms. You may close your account at any time by emailing us.
      </p>
    </LegalPage>
  );
}

export function RefundPolicy() {
  return (
    <LegalPage title="Refund Policy" updatedOn="Jan 2026">
      <p>
        We want you to get your money's worth. Read the fine print here before purchasing.
      </p>
      <h2>Subscription plans (Basic, Pro)</h2>
      <ul>
        <li>Full refund if requested within 48 hours of purchase, provided you've used fewer than 3 runs on the plan.</li>
        <li>After that, refunds are prorated at Placemint's discretion.</li>
      </ul>
      <h2>One-time bundles (MAX, SuperMAX)</h2>
      <ul>
        <li>Full refund within 48 hours if you've used fewer than 5 runs.</li>
        <li>After that, refunds are not available since the runs are consumed continuously.</li>
      </ul>
      <h2>Refund process</h2>
      <p>
        Email <a href="mailto:hello@placemint.app" className="text-pm-primary-dark underline">hello@placemint.app</a> from the address on your account with your order ID. Refunds are processed via Razorpay back to the original payment method within 5–7 business days.
      </p>
      <h2>Not refundable</h2>
      <ul>
        <li>Free-tier accounts (nothing was paid).</li>
        <li>Founder-tier gifted accounts.</li>
      </ul>
    </LegalPage>
  );
}

export function CookiePolicy() {
  return (
    <LegalPage title="Cookie Policy" updatedOn="Jan 2026">
      <p>
        Placemint uses one cookie: <code className="font-mono bg-pm-muted px-1 rounded">session_token</code>. It stores your login session so you don't have to sign in on every page. It's <strong>HttpOnly</strong>, <strong>Secure</strong>, and <strong>SameSite=None</strong>.
      </p>
      <p>
        We do not use analytics cookies, advertising cookies, or third-party tracking pixels.
      </p>
      <p>
        Clearing this cookie signs you out. You can do that any time from your browser's site settings.
      </p>
    </LegalPage>
  );
}

export function About() {
  return (
    <LegalPage title="About Placemint">
      <p>
        Placemint was built because every "placement prep" tool on the internet pretends every company runs the same test. They don't.
      </p>
      <p>
        TCS NQT has sectional cutoffs. Infosys' pseudocode round has a 65% hard gate. Wipro's essay is a real elimination step. Zoho runs a 3-round marathon spanning aptitude, 5 programs, and advanced DSA. Accenture has a gamified cognitive round. If your prep platform doesn't reflect any of that, you're preparing for the wrong test.
      </p>
      <p>
        We wrote 14 real OA structures into the engine, plumbed them through a resume checker + adaptive interview + cross-phase report, and then made the whole thing generate fresh questions on demand, so you don't just practice the same 20 leaked papers everyone else has already seen.
      </p>
      <p>
        Made in India, for the fresher who's tired of “one mock test fits all”.
      </p>
      <p>
        <a href="mailto:hello@placemint.app" className="text-pm-primary-dark underline">hello@placemint.app</a>
      </p>
    </LegalPage>
  );
}
