// Central test IDs. Keep names semantic and stable.
export const TID = {
  navLogo: "nav-logo",
  navLogin: "nav-login",
  navSignup: "nav-signup",
  navDashboard: "nav-dashboard",
  navLogout: "nav-logout",
  heroCta: "hero-start-cta",
  heroSecondary: "hero-secondary-cta",
  companyGrid: "company-grid",
  companyCard: (id) => `company-card-${id}`,
  companyStartBtn: (id) => `company-start-${id}`,
  departmentGrid: "department-grid",
  departmentCard: (id) => `department-card-${id}`,
  pricingPlan: (id) => `pricing-plan-${id}`,
  pricingSelect: (id) => `pricing-select-${id}`,
  loginEmail: "login-email",
  loginPassword: "login-password",
  loginSubmit: "login-submit",
  loginGoogle: "login-google",
  signupName: "signup-name",
  signupEmail: "signup-email",
  signupPassword: "signup-password",
  signupSubmit: "signup-submit",
  signupGoogle: "signup-google",
  resumeUploadInput: "resume-file",
  resumeRoleInput: "resume-role",
  resumeSubmit: "resume-submit",
  resumeSkip: "resume-skip",
  startOaBtn: "start-oa",
  oaTimer: "oa-timer",
  oaQuestionOption: (qid, ix) => `oa-opt-${qid}-${ix}`,
  oaEssayInput: (qid) => `oa-essay-${qid}`,
  oaCodeArea: "oa-code-area",
  oaLangSelect: "oa-lang-select",
  oaRunBtn: "oa-run-btn",
  oaNextSection: "oa-next-section",
  oaFinishSection: "oa-finish-section",
  oaCardTile: (qid, tileId) => `oa-card-tile-${qid}-${tileId}`,
  oaConnectPoint: (qid, pointId) => `oa-connect-point-${qid}-${pointId}`,
  oaConnectSubmit: (qid) => `oa-connect-submit-${qid}`,
  oaConnectUndo: (qid) => `oa-connect-undo-${qid}`,
  oaTypedInput: (qid) => `oa-typed-input-${qid}`,
  oaDigitTile: (qid, tileIx) => `oa-digit-tile-${qid}-${tileIx}`,
  oaDigitSlot: (qid, position) => `oa-digit-slot-${qid}-${position}`,
  oaPatternTile: (qid, tileIx) => `oa-pattern-tile-${qid}-${tileIx}`,
  oaMathInput: (qid) => `oa-math-input-${qid}`,
  oaMathSubmit: (qid) => `oa-math-submit-${qid}`,
  oaShapeBase: (qid) => `oa-shape-base-${qid}`,
  oaShapeOption: (qid, ix) => `oa-shape-option-${qid}-${ix}`,
  oaSortTile: (qid, itemId) => `oa-sort-tile-${qid}-${itemId}`,
  oaPathCell: (qid, cell) => `oa-path-cell-${qid}-${cell}`,
  oaPathExitOption: (qid, ix) => `oa-path-exit-${qid}-${ix}`,
  oaMazeCell: (qid, cell) => `oa-maze-cell-${qid}-${cell}`,
  oaMazeKey: (qid, keyId) => `oa-maze-key-${qid}-${keyId}`,
  clusterOption: (cluster) => `cluster-option-${cluster}`,
  oaMicRecordBtn: (qid) => `oa-mic-record-${qid}`,
  oaMicStopBtn: (qid) => `oa-mic-stop-${qid}`,
  oaTranscriptInput: (qid) => `oa-transcript-${qid}`,
  oaMicFallbackInput: (qid) => `oa-mic-fallback-${qid}`,
  motionBlock: (puzzleId, blockId) => `motion-block-${puzzleId}-${blockId}`,
  motionBall: (puzzleId) => `motion-ball-${puzzleId}`,
  motionTarget: (puzzleId, direction) => `motion-target-${puzzleId}-${direction}`,
  motionUndo: "motion-undo",
  intvAnswerInput: "intv-answer-input",
  intvSubmitAnswer: "intv-submit-answer",
  intvStartBtn: "intv-start-btn",
  finalReportView: "final-report-view",
};
